docs: add syllabus v0.1.0
TheDxns/kanban-board pull request #1
Opened 2022-12-11 10:10 UTC by schier-jonasz

2022-12-11 10:45 UTC, TheDxns requested changes
wyrzuć pls vue z tech stacku, póki co robimy tylko backend

2022-12-11 10:57 UTC, schier-jonasz commented
Wyrzucone

2022-12-11 10:57 UTC, TheDxns approved these changes

2022-12-11 10:58 UTC, TheDxns commented
> Wyrzucone

2022-12-11 10:59 UTC, TheDxns approved these changes

2022-12-12 07:58 UTC, arturwita approved these changes

2022-12-12 09:13 UTC, merged